Repository pyrsia/pyrsia, pull requests merged in 2022-04, with the labels that each got.

#539 persist the libp2p keypair
  src/network/p2p.rs
  src/util.rs
  src/util/keypair_util.rs
Labels: p2p

#565 Avoid running lint jobs if `rs` files weren't changed
  .github/workflows/lint.yml
Labels: github_actions

#582 bump actions per dependabot
  .github/workflows/lint.yml
  .github/workflows/rust.yml
Labels: dependencies, github_actions

#462 RFC Proposal Path
  docs/rfc/0000-template.md
  docs/rfc/readme.md
Labels: documentation

#593 Adding directions on updating rust toolchain.
  .github/pull_request_template.md
  docs/dev_workflow.md
Labels: documentation

#535 Add support for encoding required to use AlephBFT
  Cargo.lock
  Cargo.toml
  src/blockchain/Cargo.toml
  src/blockchain/examples/simple_node.rs
  src/blockchain/src/blockchain.rs
  src/blockchain/src/crypto/hash_algorithm.rs
  src/blockchain/src/structures/block.rs
  src/blockchain/src/structures/chain.rs
  src/blockchain/src/structures/header.rs
  src/blockchain/src/structures/transaction.rs
Labels: blockchain

#541 Demo tutorial
  docs/tutorials/demo.md
Labels: documentation, demo

#568 Add explanations for some cryptographic concept
  docs/cryptographic_key_concept.md
Labels: documentation, blockchain

#600 Drop in Aleph-BFT consensus into blockchain and example
  Cargo.lock
  src/blockchain/Cargo.toml
  src/blockchain/examples/simple_node.rs
  src/blockchain/src/crypto/hash_algorithm.rs
  src/blockchain/src/identities/verify_key.rs
  src/blockchain/src/lib.rs
  src/blockchain/src/network.rs
  src/blockchain/src/providers.rs
  src/blockchain/src/structures/block.rs
  src/blockchain/src/structures/chain.rs
  src/blockchain/src/structures/header.rs
Labels: blockchain, in-review

#616 Note some required system dependencies
  docs/local_dev_setup.md
Labels: documentation, in-review

#618 Update CLI command in readme snippet
  readme.md
Labels: documentation, in-review

#553 Writes up steps for running multiple pyrsia nodes on a macosx
  docs/setup_on_macosx.md
Labels: documentation

#629 Provision a PackageVersion after creation
  pyrsia_node/src/network/handlers.rs
  src/docker/v2/handlers/blobs.rs
  src/docker/v2/handlers/manifests.rs
  src/docker/v2/routes.rs
  src/network/client.rs
  src/network/client/command.rs
  src/network/event_loop.rs
Labels: in-review

#631 Apply strum Display macro on Command enum
  src/network/client/command.rs
Labels: in-review

#630 Create the upload directory when storing blob
  src/docker/v2/handlers/blobs.rs
  src/docker/v2/storage/blobs.rs
Labels: in-review
