Repository pyrsia/pyrsia, pull requests merged in 2022-12, with the labels that each got.

#1348 Upgrade libp2p crate
  .github/workflows/rust-lint-skipped.yml
  .github/workflows/rust-lint.yml
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  Dockerfile
  docs/community/get_involved/local_dev_setup.md
  pyrsia_node/Cargo.toml
  pyrsia_node/src/main.rs
  src/blockchain/Cargo.toml
  src/blockchain/src/args.rs
  src/blockchain/src/args/parser.rs
  src/blockchain/src/blockchain.rs
  src/blockchain/src/lib.rs
  src/blockchain/src/network.rs
  src/blockchain/src/providers.rs
  src/docker/v2/handlers/blobs.rs
  src/docker/v2/handlers/manifests.rs
  src/docker/v2/routes.rs
  src/java/maven2/handlers/maven_artifacts.rs
  src/java/maven2/routes.rs
  src/network/behaviour.rs
  src/network/event_loop.rs
  src/network/p2p.rs
  src/node_api/routes.rs
  src/util/keypair_util.rs
  src/verification_service/service.rs
Labels: in-review

#1365 update docs to use version 0.2.1 - fixes #1357
  docs/developers/build_from_source_docker.md
  docs/developers/build_from_source_maven.md
  docs/sre/kubernetes-helm.md
  docs/tutorials/docker-pull-pyrsia-decentralized-network-verification.md
  docs/tutorials/docker.md
  docs/tutorials/quick-installation.mdx
Labels: in-review

#1343 Upgrade clap crate
  Cargo.lock
  Cargo.toml
  pyrsia_cli/Cargo.toml
  pyrsia_cli/src/cli/handlers.rs
  pyrsia_cli/src/cli/parser.rs
  pyrsia_cli/src/main.rs
  pyrsia_node/Cargo.toml
  src/blockchain/Cargo.toml
Labels: in-review

#1358 pin rust to 1.65 and display rust versions
  .github/workflows/rust-lint.yml
  .github/workflows/rust.yml
  Cargo.toml
Labels: in-review

#1383 Use correct variable name for rust version
  Cargo.toml
Labels: in-review

#1367 update local dev setup documentation to reflect the latest changes
  docs/community/get_involved/local_dev_setup.md
Labels: in-review

#1384 The Clippy "large_enum_variant" warnings fix
  src/network/behaviour.rs
  src/network/event_loop.rs
Labels: in-review

#1370 Return useful error messages in the Pyrsia CLI
  pyrsia_cli/src/cli/handlers.rs
  src/artifact_service/service.rs
  src/cli_commands/node.rs
  src/docker/error_util.rs
Labels: in-review

#1386 Pin rust compiler version to Cargo.toml
  .github/workflows/rust-lint-skipped.yml
  .github/workflows/rust.yml
  Dockerfile
  installers/docker/CodeCoverage.Dockerfile
  installers/docker/CodeCoverageTest.Dockerfile
  installers/docker/local_code_coverage/Dockerfile
Labels: github_actions, rust

#1356 Updates template to require integration tests
  .github/pull_request_template.md
Labels: in-review

#1376 Pyrsia CLI Config - individual attribute configuration issue
  Cargo.lock
  Cargo.toml
  pyrsia_cli/Cargo.toml
  pyrsia_cli/src/cli/handlers.rs
  src/cli_commands/config.rs
Labels: in-review

#1406 Update build from source tutorials
  docs/developers/build_from_source_docker.md
  docs/developers/build_from_source_maven.md
Labels: in-review

#1360 Need a mechanism to determine build's state (based on the build ID) (…
  pyrsia_cli/src/cli/handlers.rs
  pyrsia_cli/src/cli/parser.rs
  pyrsia_cli/src/main.rs
  pyrsia_node/src/main.rs
  pyrsia_node/src/network/handlers.rs
  src/artifact_service/service.rs
  src/build_service/error.rs
  src/build_service/event.rs
  src/build_service/service.rs
  src/cli_commands/node.rs
  src/network.rs
  src/network/behaviour.rs
  src/network/build_status_protocol.rs
  src/network/client.rs
  src/network/client/command.rs
  src/network/event_loop.rs
  src/network/p2p.rs
  src/node_api/handlers/swarm.rs
  src/node_api/model/cli.rs
  src/node_api/routes.rs
Labels: in-review

#1408 Remove an unused type BlobDoesNotExist
  docs/community/get_involved/local_dev_setup.md
  docs/tutorials/docker.md
  pyrsia_node/readme.md
  src/docker/error_util.rs
Labels: in-review

#1405 Documents the release process for Pyrsia
  docs/developers/release_process.md
Labels: in-review

#1424 prepare 0.2.2 release
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  pyrsia_cli/Cargo.toml
  pyrsia_node/Cargo.toml
  src/blockchain/Cargo.toml
Labels: in-review

#1422 Added some clarifications to `.github/pull_request_template.md`
  .github/pull_request_template.md
Labels: in-review

#1421 Return useful messages in CLI
  pyrsia_cli/src/cli/handlers.rs
  src/cli_commands/node.rs
Labels: in-review

#1423 Replace native-tls with rustls
  Cargo.lock
  Cargo.toml
  pyrsia_cli/Cargo.toml
  pyrsia_node/Cargo.toml
Labels: rust, in-review

#1418 Fix Peer Metrics that fail intermittently
  src/peer_metrics/metrics.rs
Labels: in-review

#1436 Correct repo url and version string
  docs/sre/kubernetes-helm.md
Labels: in-review

#1431 improve release docs and include manual test plan
  docs/developers/postrelease_manual_tests.md
  docs/developers/prerelease_manual_tests.md
  docs/developers/release_process.md
Labels: in-review

#1416 Pyrsia CLI Configuration Remove Operation
  pyrsia_cli/src/cli/handlers.rs
  pyrsia_cli/src/main.rs
  src/cli_commands/config.rs
Labels: in-review

#1420 Developer onboarding resources
  docs/community/get_involved/developer_onboarding.md
Labels: in-review

#1437 pin windows and osx runners
  .github/workflows/rust-skipped.yml
  .github/workflows/rust.yml
Labels: in-review

#1439 update docs to use 0.2.2
  docs/tutorials/quick-installation.mdx
Labels: in-review

#1444 update to next release version 0.2.3
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  pyrsia_cli/Cargo.toml
  pyrsia_node/Cargo.toml
  src/blockchain/Cargo.toml
Labels: in-review

#1442 Sync index.html from GitHub Runner(src) to Google Cloud Bucket(dst)
  .github/workflows/homebrew-installer-upload.sh
Labels: in-review

#1452 Initiate kademlia bootstrap after probe or dial
  src/network/client.rs
  src/network/client/command.rs
  src/network/event_loop.rs
Labels: in-review

#1409 Blockchain broadcast 1345
  Cargo.lock
  Cargo.toml
  pyrsia_node/Cargo.toml
  pyrsia_node/src/main.rs
  pyrsia_node/src/network/handlers.rs
  src/artifact_service/service.rs
  src/blockchain/Cargo.toml
  src/blockchain/src/error.rs
  src/blockchain_service/service.rs
  src/docker/v2/handlers/blobs.rs
  src/docker/v2/handlers/manifests.rs
  src/docker/v2/routes.rs
  src/java/maven2/handlers/maven_artifacts.rs
  src/java/maven2/routes.rs
  src/network/behaviour.rs
  src/network/client.rs
  src/network/client/command.rs
  src/network/event_loop.rs
  src/network/p2p.rs
  src/node_api/routes.rs
  src/transparency_log/log.rs
  src/verification_service/service.rs
Labels: in-review

#1448 Fixed a CLI display issue - Remove duplicated quotations
  docs/developers/build_from_source_docker.md
  docs/developers/build_from_source_maven.md
  pyrsia_cli/src/cli/handlers.rs
  src/cli_commands/node.rs
Labels: in-review

#1460 Google Cloud Rsync Fix
  .github/workflows/rust.yml
Labels: in-review

#1456 Enhance the `create_transparency_log` test
  src/transparency_log/log.rs
Labels: in-review

#1451 Remove code duplications from `transparency_log` tests
  src/transparency_log/log.rs
Labels: in-review

#1463 Added check (with exit code) if openssl detected in the cargo.lock files
  .github/workflows/build.sh
Labels: in-review

#1464 Explicitly remove openssl before build if it is cached. Added dump of…
  .github/workflows/build.sh
Labels: in-review
