Repository pyrsia/pyrsia, pull requests merged in 2022-06, with the labels that each got.

#737 Improve blockchain blog diagrams
  blog/2022-01-28-blockchain-consensus.md
Labels: documentation, in-review

#739 Assign @pyrsia/collaborators to all PRs
  .github/CODEOWNERS
  .github/pull_request_template.md
Labels: github_actions, in-review

#747 Improve documentation content
  docs/get_involved/good_pr.md
  docs/get_involved/rfc/0000-template.md
  docs/get_involved/rfc/readme.md
  docs/tutorials/demo.md
  docs/tutorials/setup_on_macosx.md
  readme.md
Labels: documentation, in-review

#749 Fix spelling of `paths-ignore`
  .github/workflows/rust-lint-skipped.yml
Labels: github_actions, in-review

#753 Fix comment in trace logging of blockchain module
  src/blockchain/src/network.rs
  src/node_manager/model/artifact.rs
Labels: blockchain, in-review

#750 Update project automation with recent changes to board and codeowners
  .github/workflows/board-automation.yml
Labels: github_actions, in-review

#757 Fixed some typos
  pyrsia_node/src/main.rs
Labels: in-review

#726 Add information regarding adding blogs
  docs/get_involved/doc_workflow.md
Labels: documentation, in-review

#717 Fix bad and/or broken links in the documentation
  .github/mlc_config.json
  .github/pull_request_template.md
  .github/workflows/doc-lint.yml
  docs/get_involved/governance.md
  docs/get_involved/readme.md
  docs/get_involved/rfc/0000-template.md
  docs/get_involved/rfc/readme.md
  docs/readme.md
  docs/tutorials/demo.md
  docs/tutorials/readme.md
  docs/tutorials/setup_on_macosx.md
  readme.md
Labels: documentation, in-review

#712 Circuit Relay V2 client and DCUTR protocols for NAT Traversal
  Cargo.lock
  Cargo.toml
  pyrsia_node/Cargo.toml
  pyrsia_node/src/args/parser.rs
  pyrsia_node/src/main.rs
  src/network/behaviour.rs
  src/network/client.rs
  src/network/client/command.rs
  src/network/event_loop.rs
  src/network/p2p.rs
  src/network_central/event_loop.rs
Labels: in-review

#746 Avoid running cov jobs if `rs` files weren't changed
  .github/workflows/rust-skipped.yml
  .github/workflows/rust.yml
Labels: github_actions, in-review

#767 Revert "Circuit Relay V2 client and DCUTR protocols for NAT Traversal"
  Cargo.lock
  Cargo.toml
  pyrsia_node/Cargo.toml
  pyrsia_node/src/args/parser.rs
  pyrsia_node/src/main.rs
  src/network/behaviour.rs
  src/network/client.rs
  src/network/client/command.rs
  src/network/event_loop.rs
  src/network/p2p.rs
  src/network_central/event_loop.rs
Labels: in-review

#764 Peer Metric Blog
  blog/2022-06-03-peer-metrics.md
Labels: documentation, in-review

#774 cleanup lint warnings by updating md and implementing new linter
  .github/linters/.markdownlint.yaml
  .github/mlc_config.json
  .github/workflows/.cargo/README.md
  .github/workflows/doc-lint.yml
  blog/2022-01-28-blockchain-consensus.md
  blog/2022-06-03-peer-metrics.md
  docs/developers/pyrsia-high-level-overview.md
  docs/get_involved/dev_workflow.md
  docs/get_involved/doc_workflow.md
  docs/get_involved/governance.md
  docs/get_involved/local_dev_setup.md
  docs/get_involved/readme.md
  docs/get_involved/rfc/0000-template.md
  docs/get_involved/rfc/readme.md
  docs/social.mdx
  docs/tutorials/demo.md
  docs/tutorials/setup_on_macosx.md
  readme.md
  src/blockchain/readme.md
  src/readme.md
Labels: in-review

#783 Pyrsia architecture and use cases document
  docs/developers/pyrsia-architecture-and-use-cases.md
  docs/developers/pyrsia-high-level-overview.md
  docs/developers/pyrsia-network1.png
  docs/developers/pyrsia-network2.png
  docs/developers/pyrsia-node-high-level-components.png
Labels: in-review

#778 ArtifactManager and docker component refactoring
  .gitignore
  Cargo.lock
  Cargo.toml
  pyrsia_central_node/Cargo.toml
  pyrsia_central_node/src/args.rs
  pyrsia_central_node/src/args/parser.rs
  pyrsia_central_node/src/main.rs
  pyrsia_central_node/src/network.rs
  pyrsia_central_node/src/network/handlers.rs
  pyrsia_node/src/main.rs
  pyrsia_node/src/network/handlers.rs
  src/artifact_service.rs
  src/artifact_service/handlers.rs
  src/artifact_service/service.rs
  src/artifact_service/storage.rs
  src/artifacts_repository.rs
  src/artifacts_repository/artifact_manager.rs
  src/build_service.rs
  src/build_service/service.rs
  src/cli_commands/node.rs
  src/docker.rs
  src/docker/docker_hub_util.rs
  src/docker/error_util.rs
  src/docker/v2.rs
  src/docker/v2/handlers.rs
  src/docker/v2/handlers/blobs.rs
  src/docker/v2/handlers/manifests.rs
  src/docker/v2/routes.rs
  src/docker/v2/storage/blobs.rs
  src/document_store.rs
  src/document_store/document_store.rs
  src/lib.rs
  src/metadata_manager.rs
  src/metadata_manager/metadata.rs
  src/network/artifact_protocol.rs
  src/network/client.rs
  src/network_central/behaviour.rs
  src/network_central/event_loop.rs
  src/network_central/p2p.rs
  src/node_api.rs
  src/node_api/handlers/swarm.rs
  src/node_api/model.rs
  src/node_api/model/cli.rs
  src/node_api/routes.rs
  src/node_manager/model/artifact.rs
  src/node_manager/model/namespace.rs
  src/node_manager/model/package.rs
  src/node_manager/model/package_version.rs
  src/transparency_log/log.rs
  src/util.rs
  src/util/test_util.rs
Labels: in-review

#785 use workflow identity instead of keys
  .github/workflows/rust.yml
Labels: in-review

#776 Definition of Transparent Log Signature Structure
  src/artifact_service/handlers.rs
  src/transparency_log/log.rs
Labels: in-review

#787 fix broken links in blog
  blog/2022-01-28-blockchain-consensus.md
  docs/get_involved/dev_workflow.md
Labels: in-review

#751 Implement verification on transparency log
  pyrsia_node/Cargo.toml
  src/artifact_service/handlers.rs
  src/docker/error_util.rs
  src/docker/v2/handlers/blobs.rs
  src/docker/v2/handlers/manifests.rs
  src/docker/v2/routes.rs
  src/transparency_log/log.rs
Labels: transparency log, in-review

#796 Replace assay tests with regular tests
  Cargo.lock
  Cargo.toml
  pyrsia_node/src/main.rs
  src/artifact_service/handlers.rs
  src/artifact_service/storage.rs
  src/blockchain/examples/simple_node.rs
  src/cli_commands/config.rs
  src/docker/v2/handlers/blobs.rs
  src/docker/v2/handlers/manifests.rs
  src/transparency_log/log.rs
  src/util/env_util.rs
  src/util/keypair_util.rs
  src/util/test_util.rs
Labels: in-review

#799 Use database for transparency log transaction logs
  Cargo.lock
  Cargo.toml
  src/transparency_log/log.rs
Labels: in-review

#790 Dial might never return
  pyrsia_node/src/main.rs
  pyrsia_node/src/network/handlers.rs
  src/network/behaviour.rs
  src/network/client.rs
  src/network/client/command.rs
  src/network/event_loop.rs
  src/network/p2p.rs
Labels: in-review

#800 Updates demo instructions to a release version instead of main
  docs/tutorials/setup_on_macosx.md
Labels: in-review

#797 Addition of glossary
  docs/glossary.md
Labels: in-review

#810 Fix broken link
  docs/tutorials/setup_on_macosx.md
Labels: in-review

#812 Update if-watch to v1.1.1
  Cargo.lock
  Cargo.toml
Labels: in-review

#805 More detailed Pyrsia components and stories
  docs/developers/pyrsia-architecture-and-use-cases.md
  docs/developers/pyrsia-node-high-level-components.png
Labels: in-review
