Repository pyrsia/pyrsia, pull requests merged in 2022-10, with the labels that each got.

#1111 Implement blockchain initialization
  pyrsia_node/src/args/parser.rs
  pyrsia_node/src/main.rs
  src/artifact_service/service.rs
  src/blockchain/src/blockchain.rs
  src/blockchain_service/service.rs
  src/docker/v2/handlers/blobs.rs
  src/docker/v2/handlers/manifests.rs
  src/docker/v2/routes.rs
  src/java/maven2/handlers/maven_artifacts.rs
  src/java/maven2/routes.rs
  src/network/p2p.rs
  src/node_api/routes.rs
  src/transparency_log/log.rs
  src/verification_service/service.rs
Labels: in-review

#1132 Write pulled blocks at initialization to transparency log
  docs/tutorials/build_from_source_docker.md
  docs/tutorials/build_from_source_maven.md
  installers/docker/node-entrypoint.sh
  pyrsia_node/src/args/parser.rs
  pyrsia_node/src/main.rs
  src/artifact_service/service.rs
  src/blockchain_service/service.rs
  src/docker/error_util.rs
  src/java/maven2/routes.rs
  src/transparency_log/log.rs
Labels: in-review

#1134 Add --init-blockchain and update to run on nightly cluster
  .github/workflows/rust.yml
  installers/docker/AptGet.Dockerfile
  installers/docker/node-entrypoint.sh
  installers/helm/pyrsia-node/Chart.yaml
  installers/helm/pyrsia-node/templates/clusterrole.yaml
  installers/helm/pyrsia-node/templates/deployment.yaml
  installers/helm/pyrsia-node/templates/service.yaml
  installers/helm/pyrsia-node/values.yaml
Labels: in-review

#1137 Use warnings instead of pull_block errors to avoid exiting the process
  src/blockchain/src/blockchain.rs
  src/blockchain/src/structures/chain.rs
Labels: in-review

#1117 1011 Create Windows installer
  .github/workflows/rust.yml
  .github/workflows/sccache-windows.bat
  installers/windows/InstallNSSM.ps1
  installers/windows/InstallPyrsiaNodeAsWindowsService.ps1
  installers/windows/Readme.txt
  installers/windows/Readme_service.txt
  installers/windows/installer.wxs
  installers/windows/installerps1.wxs
Labels: in-review

#1056 1000 docs restructure
  .github/linters/.markdownlint.yaml
  docs/community/readme.md
  docs/developers/build_from_source_docker.md
  docs/developers/build_from_source_maven.md
  docs/developers/demo.md
  docs/developers/maven_and_pyrsia.md
  docs/developers/pyrsia-architecture-and-use-cases.md
  docs/developers/pyrsia-autonat.md
  docs/developers/pyrsia-with-docker.md
  docs/developers/readme.md
  docs/developers/setting_up_ide.md
  docs/readme.md
  docs/tutorials/docker.md
  docs/tutorials/maven.md
  docs/tutorials/quick-installation.mdx
  docs/tutorials/readme.md
  docs/tutorials/setup_on_macosx.md
  docs/tutorials/what_is_pyrsia.md
Labels: in-review

#1147 Adding --pipeline-service-endpoint to boot.pyrsia.link
  installers/docker/node-entrypoint.sh
  installers/helm/pyrsia-node/README.md
  installers/helm/pyrsia-node/templates/deployment.yaml
  installers/helm/pyrsia-node/templates/external-dns.yaml
  installers/helm/pyrsia-node/templates/service.yaml
  installers/helm/pyrsia-node/values.yaml
Labels: in-review

#1143 Fix powershell scripts
  .github/workflows/rust-skipped.yml
  .github/workflows/rust.yml
  installers/windows/InstallNSSM.ps1
  installers/windows/InstallPyrsiaNodeAsWindowsService.ps1
  installers/windows/installerps1.wxs
Labels: in-review

#1145 Blockchain persistence
  .gitignore
  Cargo.lock
  pyrsia_node/src/main.rs
  src/artifact_service/service.rs
  src/blockchain/Cargo.toml
  src/blockchain/src/blockchain.rs
  src/blockchain/src/error.rs
  src/blockchain/src/identities/authority_verifier.rs
  src/blockchain/src/identities/key_box.rs
  src/blockchain/src/structures/chain.rs
  src/blockchain/src/structures/header.rs
  src/blockchain_service/service.rs
  src/docker/v2/handlers/blobs.rs
  src/docker/v2/handlers/manifests.rs
  src/docker/v2/routes.rs
  src/java/maven2/handlers/maven_artifacts.rs
  src/java/maven2/routes.rs
  src/network/client.rs
  src/node_api/routes.rs
  src/transparency_log/log.rs
  src/verification_service/service.rs
Labels: in-review

#1155 Upload each MSI installer in its own zip
  .github/workflows/rust.yml
Labels: in-review

#1157 increase version to 0.2.0
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  pyrsia_cli/Cargo.toml
  pyrsia_node/Cargo.toml
  src/blockchain/Cargo.toml
Labels: in-review

#1172 improve readme
  readme.md
Labels: in-review

#1186 Improve tutorials for Docker setup
  docs/tutorials/docker.md
  docs/tutorials/quick-installation.mdx
  readme.md
Labels: in-review

#1173 Pyrsia MacOS Installer using Homebrew Automation
  .github/workflows/homebrew-installer-upload.sh
  .github/workflows/rust.yml
Labels: in-review

#1209 Fix "Pyrsia MacOS Installer using Homebrew Automation" (PR#1173)
  .github/workflows/rust.yml
Labels: in-review

#1191 Update links in a PR template to avoid 404
  .github/pull_request_template.md
Labels: in-review

#1206 Increase the maximum size of each message in the blockchain to 10MB
  src/blockchain_service/service.rs
  src/network/blockchain_protocol.rs
Labels: in-review

#1211 Refactor blockchain debug information
  src/blockchain_service/service.rs
  src/network/blockchain_protocol.rs
  src/network/client.rs
Labels: in-review

#1185 New homebrew and windows repo websites
  installers/docker/NginxGcsFuse.Dockerfile
  installers/helm/pyrsia-brewrepo/.helmignore
  installers/helm/pyrsia-brewrepo/Chart.yaml
  installers/helm/pyrsia-brewrepo/templates/_helpers.tpl
  installers/helm/pyrsia-brewrepo/templates/deployment.yaml
  installers/helm/pyrsia-brewrepo/templates/ingress.yaml
  installers/helm/pyrsia-brewrepo/templates/managed-cert.yaml
  installers/helm/pyrsia-brewrepo/templates/service.yaml
  installers/helm/pyrsia-brewrepo/values.yaml
  installers/helm/pyrsia-winrepo/.helmignore
  installers/helm/pyrsia-winrepo/Chart.yaml
  installers/helm/pyrsia-winrepo/templates/_helpers.tpl
  installers/helm/pyrsia-winrepo/templates/deployment.yaml
  installers/helm/pyrsia-winrepo/templates/ingress.yaml
  installers/helm/pyrsia-winrepo/templates/managed-cert.yaml
  installers/helm/pyrsia-winrepo/templates/service.yaml
  installers/helm/pyrsia-winrepo/values.yaml
Labels: in-review, website

#1212 remove use of `-H 0.0.0.0` in docs
  docs/developers/build_from_source_docker.md
  docs/developers/setting_up_ide.md
  docs/tutorials/docker.md
  readme.md
Labels: in-review

#1214 improve inspect-log output
  Cargo.lock
  docs/tutorials/quick-installation.mdx
  pyrsia_cli/Cargo.toml
  pyrsia_cli/src/cli/handlers.rs
Labels: in-review

#1218 Make blockchain debug info more readable and fix typos
  pyrsia_node/src/main.rs
  pyrsia_node/src/network/handlers.rs
  src/blockchain_service/service.rs
  src/network/client.rs
Labels: in-review

#1215 Verify that build can be done
  src/artifact_service/service.rs
  src/build_service/error.rs
  src/docker/error_util.rs
  src/transparency_log/log.rs
Labels: in-review

#1210 Fixes PR#1209
  .github/workflows/homebrew-installer-upload.sh
  .github/workflows/rust.yml
Labels: in-review

#1223 Add env var PYRSIA_BLOCKCHAIN_PATH=/usr/local/var/pyrsia/blockchain
  Dockerfile
  installers/debian/pyrsia.service
  installers/helm/pyrsia-node/templates/deployment.yaml
Labels: in-review

#1227 Do not propagate blockchain broadcast errors
  src/blockchain_service/service.rs
Labels: in-review

#1226 Build docker image on a release
  .github/workflows/rust.yml
Labels: github_actions, in-review

#1232 Provide local artifacts
  pyrsia_node/src/main.rs
  src/artifact_service/service.rs
  src/artifact_service/storage.rs
Labels: in-review

#1225 Remove blogs
  blog/2022-01-28-blockchain-consensus.md
  blog/2022-06-03-peer-metrics.md
  installers/windows/Readme.txt
  readme.md
Labels: in-review

#1219 Homebrew Quick Installer Guide for macOS Users
  docs/tutorials/quick-installation.mdx
Labels: in-review

#1182 Updates readme for windows installer
  installers/windows/Readme.txt
Labels: in-review

#1233 restart pod when unhealthy and deploy service based on replica Count
  installers/helm/pyrsia-node/templates/deployment.yaml
  installers/helm/pyrsia-node/templates/service.yaml
Labels: central node, in-review

#1235 Add notes to show what is not implemented
  docs/tutorials/docker.md
Labels: in-review

#1238 Links the installers to the top of the page
  docs/tutorials/quick-installation.mdx
Labels: in-review

#1237 Delete outdated docs
  docs/developers/maven_and_pyrsia.md
  docs/developers/pyrsia-with-docker.md
  docs/developers/setting_up_ide.md
  docs/glossary.md
  docs/social.mdx
  pyrsia_cli/readme.md
  readme.md
Labels: in-review

#1240 Bug - macos installer automation::gsutil rsync
  .github/workflows/homebrew-installer-upload.sh
Labels: in-review

#1241 More docs changes
  docs/developers/demo.md
  docs/developers/readme.md
  docs/tutorials/maven.md
  docs/tutorials/readme.md
Labels: in-review
