Repository pyrsia/pyrsia, pull requests merged in 2022-05, with the labels that each got.

#638 Proposing a fix for issue found with config file losing configured va…
  src/cli_commands/config.rs
Labels: in-review

#639 Improve headings for new website
  docs/cryptographic_key_concept.md
  docs/local_dev_setup.md
  docs/tutorials/setup_on_macosx.md
Labels: documentation, in-review

#646 Refactor blockchain logging
  .github/workflows/lint.yml
  src/blockchain/examples/simple_node.rs
Labels: in-review

#650 Generate pretty directory listing web pages for repo and fix demo script workflow
  .github/workflows/aptly.sh
  .github/workflows/demo.yml
  .github/workflows/genlisting.py
Labels: in-review

#656 Fixes typo
  docs/cryptographic_key_concept.md
Labels: in-review

#644 Provision package versions at startup
  pyrsia_node/src/network/handlers.rs
  src/document_store/document_store.rs
  src/metadata_manager/metadata.rs
  src/node_manager/handlers.rs
Labels: in-review

#654 Update project description with new language
  pyrsia_cli/Cargo.toml
  pyrsia_cli/readme.md
  pyrsia_node/Cargo.toml
  readme.md
Labels: documentation, in-review

#657 Refactor blockchain CLI
  Cargo.lock
  Cargo.toml
  src/blockchain/Cargo.toml
  src/blockchain/examples/simple_node.rs
  src/blockchain/src/args.rs
  src/blockchain/src/args/parser.rs
  src/blockchain/src/lib.rs
Labels: blockchain, in-review

#665 Minor touch ups to RFC template
  docs/rfc/0000-template.md
Labels: documentation, in-review

#574 Peer metric
  Cargo.lock
  Cargo.toml
  pyrsia_node/src/main.rs
  pyrsia_node/src/network/handlers.rs
  src/docker/v2/handlers/blobs.rs
  src/network.rs
  src/network/behaviour.rs
  src/network/client.rs
  src/network/client/command.rs
  src/network/event_loop.rs
  src/network/idle_metric_protocol.rs
  src/network/p2p.rs
  src/node_manager/handlers.rs
Labels: p2p, in-review

#669 Delete cryptographic_key_concept.md
  docs/cryptographic_key_concept.md
Labels: documentation, in-review

#681 Update document structure for website
  docs/get_involved/dev_workflow.md
  docs/get_involved/good_pr.md
  docs/get_involved/governance.md
  docs/get_involved/local_dev_setup.md
  docs/get_involved/readme.md
  docs/get_involved/rfc/0000-template.md
  docs/get_involved/rfc/readme.md
  docs/get_involved/things-to-know.md
  docs/readme.md
  docs/social.mdx
  docs/tutorials/quick-installation.mdx
  docs/tutorials/readme.md
Labels: documentation, in-review

#683 Minor adjustments to improve website navigation
  docs/get_involved/local_dev_setup.md
  docs/get_involved/readme.md
  docs/readme.md
  docs/tutorials/quick-installation.mdx
Labels: documentation, in-review

#671 Refactor blockchain CLI: add -I argument to specify node index
  src/blockchain/examples/simple_node.rs
  src/blockchain/src/args/parser.rs
Labels: in-review

#667 CLI "pyrsia status" total artifacts explanation
  docs/get_involved/local_dev_setup.md
  docs/tutorials/demo.md
  docs/tutorials/setup_on_macosx.md
  readme.md
  src/artifacts_repository/artifact_manager.rs
  src/node_api/handlers/swarm.rs
  src/node_manager/handlers.rs
  src/node_manager/model/cli.rs
Labels: in-review

#685 Update experts "coffee" links in documentation
  docs/social.mdx
Labels: documentation, in-review

#691 added summary of the MVP architecture discussions
  docs/developers/pyrsia-high-level-overview.md
  docs/developers/pyrsia-node-high-level-components.png
Labels: documentation, in-review

#692 Lint markdown documentation and validate links
  .github/workflows/doc-lint.yml
  .github/workflows/md-docs-matchers.json
  .github/workflows/rust-lint.yml
Labels: documentation, github_actions, in-review

#704 allow larger number of keys to be provided
  pyrsia_node/src/args/parser.rs
  pyrsia_node/src/main.rs
  src/network/p2p.rs
Labels: in-review

#700 Add workaround for missing status checks in CI
  .github/workflows/rust-lint-skipped.yml
  .github/workflows/rust-lint.yml
Labels: github_actions, in-review

#708 Propagate channel errors instead of panicking
  pyrsia_central_node/src/args/parser.rs
  pyrsia_central_node/src/main.rs
  pyrsia_central_node/src/network/handlers.rs
  pyrsia_node/src/main.rs
  pyrsia_node/src/network/handlers.rs
  src/docker/v2/handlers/blobs.rs
  src/docker/v2/handlers/manifests.rs
  src/network/client.rs
  src/network/client/command.rs
  src/network/event_loop.rs
  src/network/p2p.rs
  src/network_central/event_loop.rs
  src/network_central/p2p.rs
  src/node_api/handlers/swarm.rs
Labels: in-review

#709 Configure website's navigation order
  docs/developers/pyrsia-high-level-overview.md
  docs/developers/readme.md
  docs/get_involved/readme.md
  docs/readme.md
  docs/tutorials/quick-installation.mdx
  docs/tutorials/readme.md
Labels: documentation, in-review

#718 Updates the MacOSX demo tutorial to clarify CLI commands
  docs/tutorials/setup_on_macosx.md
Labels: documentation, in-review

#716 Attempt to fix auto assignment of collaborators
  .github/workflows/board-automation.yml
Labels: github_actions

#694 Addition of relevant documentation about adding documentation
  docs/get_involved/doc_workflow.md
Labels: documentation, in-review

#720 Create first blog post
  blog/2022-01-28-blockchain-consesns.md
Labels: documentation, in-review

#723 Update development phase to reflect new releases
  readme.md
Labels: documentation, in-review
